<center><h1>Ye_Jinyi_HW3</h1></center>
<br>
<br>

Name: Jinyi Ye
<br>
Github Username: angelayejinyi
<br>
USC ID: 1552624974

## 1. Time Series Classification Part 1: Feature Creation/Extraction

### (a) Download Data

Package imports

In [1]:
import numpy as np
import pandas as pd
import os

Get the AReM Data Set

In [3]:
# read the datasets into a dictionary
d = {}
for root, dirs, files in os.walk('data/AReM'):
  for name in sorted(files):
    #print(sorted(files))
    print(os.path.join(root, name))
    df = pd.read_csv(os.path.join(root, name), skiprows=4)
    d[os.path.join(root, name)] = df

data/AReM/bending1/dataset1.csv
data/AReM/bending1/dataset2.csv
data/AReM/bending1/dataset3.csv
data/AReM/bending1/dataset4.csv
data/AReM/bending1/dataset5.csv
data/AReM/bending1/dataset6.csv
data/AReM/bending1/dataset7.csv
data/AReM/walking/dataset1.csv
data/AReM/walking/dataset10.csv
data/AReM/walking/dataset11.csv
data/AReM/walking/dataset12.csv
data/AReM/walking/dataset13.csv
data/AReM/walking/dataset14.csv
data/AReM/walking/dataset15.csv
data/AReM/walking/dataset2.csv
data/AReM/walking/dataset3.csv
data/AReM/walking/dataset4.csv
data/AReM/walking/dataset5.csv
data/AReM/walking/dataset6.csv
data/AReM/walking/dataset7.csv
data/AReM/walking/dataset8.csv
data/AReM/walking/dataset9.csv
data/AReM/bending2/dataset1.csv
data/AReM/bending2/dataset2.csv
data/AReM/bending2/dataset3.csv
data/AReM/bending2/dataset4.csv
data/AReM/bending2/dataset5.csv
data/AReM/bending2/dataset6.csv
data/AReM/standing/dataset1.csv
data/AReM/standing/dataset10.csv
data/AReM/standing/dataset11.csv
data/AReM/standing/dataset12.csv
data/AReM/standing/dataset13.csv
data/AReM/standing/dataset14.csv
data/AReM/standing/dataset15.csv
data/AReM/standing/dataset2.csv
data/AReM/standing/dataset3.csv
data/AReM/standing/dataset4.csv
data/AReM/standing/dataset5.csv
data/AReM/standing/dataset6.csv
data/AReM/standing/dataset7.csv
data/AReM/standing/dataset8.csv
data/AReM/standing/dataset9.csv
data/AReM/sitting/dataset1.csv
data/AReM/sitting/dataset10.csv
data/AReM/sitting/dataset11.csv
data/AReM/sitting/dataset12.csv
data/AReM/sitting/dataset13.csv
data/AReM/sitting/dataset14.csv
data/AReM/sitting/dataset15.csv
data/AReM/sitting/dataset2.csv
data/AReM/sitting/dataset3.csv
data/AReM/sitting/dataset4.csv
data/AReM/sitting/dataset5.csv
data/AReM/sitting/dataset6.csv
data/AReM/sitting/dataset7.csv
data/AReM/sitting/dataset8.csv
data/AReM/sitting/dataset9.csv
data/AReM/lying/dataset1.csv
data/AReM/lying/dataset10.csv
data/AReM/lying/dataset11.csv
data/AReM/lying/dataset12.csv
data/AReM/lying/dataset13.csv
data/AReM/lying/dataset14.csv
data/AReM/lying/dataset15.csv
data/AReM/lying/dataset2.csv
data/AReM/lying/dataset3.csv
data/AReM/lying/dataset4.csv
data/AReM/lying/dataset5.csv
data/AReM/lying/dataset6.csv
data/AReM/lying/dataset7.csv
data/AReM/lying/dataset8.csv
data/AReM/lying/dataset9.csv
data/AReM/cycling/dataset1.csv
data/AReM/cycling/dataset10.csv
data/AReM/cycling/dataset11.csv
data/AReM/cycling/dataset12.csv
data/AReM/cycling/dataset13.csv
data/AReM/cycling/dataset14.csv
data/AReM/cycling/dataset15.csv
data/AReM/cycling/dataset2.csv
data/AReM/cycling/dataset3.csv
data/AReM/cycling/dataset4.csv
data/AReM/cycling/dataset5.csv
data/AReM/cycling/dataset6.csv
data/AReM/cycling/dataset7.csv
data/AReM/cycling/dataset8.csv
data/AReM/cycling/dataset9.csv

### (b) Test and Train Data

In [44]:
test_dict = {}
test_file_lst = ['data/AReM/bending1/dataset1.csv',
                'data/AReM/bending1/dataset2.csv',
                'data/AReM/bending2/dataset1.csv',
                'data/AReM/bending2/dataset2.csv',
                'data/AReM/cycling/dataset1.csv',
                'data/AReM/cycling/dataset2.csv',
                'data/AReM/cycling/dataset3.csv',
                'data/AReM/lying/dataset1.csv',
                'data/AReM/lying/dataset2.csv',
                'data/AReM/lying/dataset3.csv',
                'data/AReM/sitting/dataset1.csv',
                'data/AReM/sitting/dataset2.csv',
                'data/AReM/sitting/dataset3.csv',
                'data/AReM/standing/dataset1.csv',
                'data/AReM/standing/dataset2.csv',
                'data/AReM/standing/dataset3.csv',
                'data/AReM/walking/dataset1.csv',
                'data/AReM/walking/dataset2.csv',
                'data/AReM/walking/dataset3.csv']
for key in test_file_lst:
    test_dict[key] = d[key]

train_dict = {}
for key,value in d.items():
    train_dict[key] = d[key]
for key in test_file_lst:
    train_dict.pop(key)

### (c) Feature Extraction

#### i. Research

Mean: The average value of the time series data.

Standard deviation: A measure of the spread of the time series data around the mean.

Maximum and minimum values: The highest and lowest values in the time series data.

Median: The middle value of the time series data when it is sorted in ascending or descending order.

Range: The difference between the maximum and minimum values.

Interquartile range (IQR): A measure of the spread of the time series data that is calculated as the difference between the 75th and 25th percentiles.

Kurtosis: A measure of the "peakedness" of the distribution of the time series data, relative to a normal distribution.

Skewness: A measure of the asymmetry of the distribution of the time series data around the mean.

Root mean square (RMS): The square root of the mean of the squares of the time series data.

Autocorrelation: A measure of the correlation between a time series and a lagged version of itself.

#### ii. Extraction

In [153]:
summary_df = pd.DataFrame(columns=['Instance', 'min1', 'max1', 'mean1', 'median1', 'std1', 'first_quart1', 'third_quart1',
                                    'min2', 'max2', 'mean2', 'median2', 'std2', 'first_quart2', 'third_quart2',
                                    'min3', 'max3', 'mean3', 'median3', 'std3', 'first_quart3', 'third_quart3',
                                    'min4', 'max4', 'mean4', 'median4', 'std4', 'first_quart4', 'third_quart4',
                                    'min5', 'max5', 'mean5', 'median5', 'std5', 'first_quart5', 'third_quart5',
                                    'min6', 'max6', 'mean6', 'median6', 'std6', 'first_quart6', 'third_quart6','label'])
i = 0

for key,value in sorted(d.items()):
    for n in range(1,7):
        globals()['min%s' % n] = value.iloc[:,n].min()
        globals()['max%s' % n] = value.iloc[:,n].max()
        globals()['mean%s' % n] = value.iloc[:,n].mean()
        globals()['median%s' % n] = value.iloc[:,n].median()
        globals()['std%s' % n] = value.iloc[:,n].std()
        globals()['first_quart%s' % n] = value.iloc[:,n].quantile(.25)
        globals()['third_quart%s' % n] = value.iloc[:,n].quantile(.75)
    label = (key.split('data/AReM/'))[1].split('/dataset')[0]
    i += 1
    summary_df.loc[len(summary_df.index)] = [int(i), min1, max1, mean1, median1, std1, first_quart1, third_quart1,
                                                min2, max2, mean2, median2, std2, first_quart2, third_quart2,
                                                min3, max3, mean3, median3, std3, first_quart3, third_quart3,
                                                min4, max4, mean4, median4, std4, first_quart4, third_quart4,
                                                min5, max5, mean5, median5, std5, first_quart5, third_quart5,
                                                min6, max6, mean6, median6, std6, first_quart6, third_quart6, label]

In [154]:
summary_df['Instance'] = summary_df['Instance'].astype(int)
summary_df

,Instance,min1,max1,mean1,median1,std1,first_quart1,third_quart1,min2,max2,...,first_quart5,third_quart5,min6,max6,mean6,median6,std6,first_quart6,third_quart6,label
0,1,37.25,45.00,40.624792,40.500,1.476967,39.25,42.0000,0.0,1.30,...,33.0000,36.00,0.0,1.92,0.570583,0.430,0.582915,0.00,1.3000,bending1
1,2,38.00,45.67,42.812812,42.500,1.435550,42.00,43.6700,0.0,1.22,...,32.0000,34.50,0.0,3.11,0.571083,0.430,0.601010,0.00,1.3000,bending1
2,3,35.00,47.40,43.954500,44.330,1.558835,43.00,45.0000,0.0,1.70,...,35.3625,36.50,0.0,1.79,0.493292,0.430,0.513506,0.00,0.9400,bending1
3,4,33.00,47.75,42.179813,43.500,3.670666,39.15,45.0000,0.0,3.00,...,30.4575,36.33,0.0,2.18,0.613521,0.500,0.524317,0.00,1.0000,bending1
4,5,33.00,45.75,41.678063,41.750,2.243490,41.33,42.7500,0.0,2.83,...,28.4575,31.25,0.0,1.79,0.383292,0.430,0.389164,0.00,0.5000,bending1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83,84,20.75,46.25,34.763333,35.290,4.742208,31.67,38.2500,0.0,12.68,...,14.2500,18.33,0.0,9.39,3.288271,3.270,1.647528,2.05,4.3050,walking
84,85,21.50,51.00,34.935813,35.500,4.645944,32.00,38.0625,0.0,12.21,...,14.2375,18.25,0.0,10.21,3.280021,3.015,1.700918,2.12,4.5000,walking
85,86,18.33,47.67,34.333042,34.750,4.948770,31.25,38.0000,0.0,12.48,...,13.7500,18.00,0.0,8.01,3.261583,2.980,1.617290,2.05,4.3200,walking
86,87,18.33,45.75,34.599875,35.125,4.731790,31.50,38.0000,0.0,15.37,...,14.0000,18.25,0.0,8.86,3.289542,3.015,1.680170,2.12,4.2600,walking
87,88,15.50,43.67,34.225875,34.750,4.441798,31.25,37.2500,0.0,17.24,...,14.3300,18.25,0.0,9.42,3.479542,3.270,1.761146,2.24,4.5375,walking

#### iii. Standard Deviation

In [150]:
from scipy import stats

# bootstrapping to find confidence interval
def draw_bs_replicates(data,func,size):
    # Create an empty array to store replicates
    bs_replicates = np.empty(size)
    
    # Create bootstrap replicates as much as size
    for i in range(size):
        # Create a bootstrap sample
        bs_sample = np.random.choice(data,len(data))
        # Get bootstrap replicate and append to bs_replicates
        bs_replicates[i] = func(bs_sample)
    
    return bs_replicates

# reference: https://towardsdatascience.com/calculating-confidence-interval-with-bootstrapping-872c657c058d

In [151]:
std_df = pd.DataFrame(columns=['feature','std'])

for column in summary_df.iloc[:,1:43].columns:
    #print(column)
    bs_replicates = draw_bs_replicates(summary_df[column], np.std, 10000)
    conf_interval = np.nanpercentile(bs_replicates,[5,95])
    std_df.loc[len(std_df)] = [column, np.around(conf_interval,3)]

In [152]:
std_df

         feature              std
0           min1  [7.512, 10.035]
1           max1   [3.025, 5.175]
2          mean1   [4.191, 5.298]
3        median1   [4.223, 5.382]
4           std1   [1.539, 1.934]
5   first_quart1    [5.06, 6.137]
6   third_quart1   [3.748, 5.356]
7           min2       [0.0, 0.0]
8           max2   [4.612, 5.482]
9          mean2    [1.39, 1.725]
10       median2   [1.238, 1.569]
11          std2    [0.81, 0.957]
12  first_quart2   [0.822, 1.042]
13  third_quart2   [1.896, 2.325]
14          min3   [2.812, 3.192]
15          max3   [3.862, 5.301]
16         mean3   [3.101, 4.311]
17       median3     [3.06, 4.34]
18          std3   [0.783, 1.199]
19  first_quart3   [3.378, 4.627]
20  third_quart3   [3.212, 4.464]
21          min4       [0.0, 0.0]
22          max4    [2.05, 2.481]
23         mean4   [1.076, 1.229]
24       median4   [1.047, 1.199]
25          std4   [0.429, 0.501]
26  first_quart4   [0.763, 0.887]
27  third_quart4   [1.428, 1.635]
28          min5   [3.386, 6.817]
29          max5    [4.338, 6.39]
30         mean5   [3.654, 6.269]
31       median5   [3.744, 6.531]
32          std5   [0.785, 1.258]
33  first_quart5   [4.042, 6.819]
34  third_quart5   [3.604, 6.096]
35          min6     [0.0, 0.088]
36          max6   [2.227, 2.827]
37         mean6   [1.067, 1.226]
38       median6   [0.998, 1.163]
39          std6   [0.473, 0.544]
40  first_quart6   [0.702, 0.822]
41  third_quart6    [1.408, 1.62]

#### iv. Select Features

Intuitively, the features that are most distinguishable between classes should have relatively large standard deviation, which suggests significant differences between classess. Besides, the 90% confidence interval should be relatively dispersed, which indicates that the data points are unevenly and widely distributed. 

Following the above criteria, I thus select <b>max, mean and third quartile</b> as the top3 features.

## 2. ISLR 3.7.4

### (a) Linear Train

I anticipate that the training RSS of polynomial regression will be less than that of linear regression because it can better fit data that has a wider irreducible error, resulting in a tighter fit.

### (b) Linear Test

I anticipate that the test RSS of polynomial regression will be greater than that of linear regression because the overfitting from the training phase would result in more error.

### (c) Not Linear Train

Polynomial regression exhibits a lower training RSS than linear regression due to its greater flexibility, as it can more closely track data points and minimize the training RSS, regardless of the true underlying relationship.

### (d) Not Linear Testing

In this case, it is hard to tell which regression would have a lower test RSS. If the data is closer to linear than cubic, the linear regression could have a lower test RSS than the cubic regression, or vice versa. This is because of the trade-off between bias and variance: it's unclear which level of flexibility would better fit the data.

## 3. ISLR 3.7.3 - Extra Practice

## 3. ISLR 3.7.5 - Extra Practice